const mongoose = require('mongoose');

const guildConfigSchema = new mongoose.Schema({
  guildId: { type: String, required: true, unique: true },
  prefix: { type: [String], default: ['.', '/'] },
  welcomeChannel: String,
  farewellChannel: String,
  boosterChannel: String,
  levelingChannel: String,
  welcomeMessage: { type: String, default: 'Welcome {user} to {server}!' },
  farewellMessage: { type: String, default: 'Goodbye {user}!' },
  boosterMessage: { type: String, default: 'Thank you {user} for boosting {server}!' },
  welcomeEmbed: { type: Boolean, default: false },
  farewellEmbed: { type: Boolean, default: false },
  boosterEmbed: { type: Boolean, default: false },
  loggingChannel: String,
  loggingEnabled: { type: Boolean, default: false },
  automodEnabled: { type: Boolean, default: false },
  antinukeEnabled: { type: Boolean, default: false },
  verifyChannel: String,
  verifyRole: String,
  verifyLogChannel: String,
  verifyMode: { type: String, enum: ['button', 'captcha', 'reaction'], default: 'button' },
  verifyMessage: { type: String, default: 'Click the button below to verify yourself.' },
  verifyEnabled: { type: Boolean, default: false },
  jailRole: String,
  muteRole: String,
  ticketChannel: String,
  ticketCategory: String,
  ticketSupportRole: String,
  ticketLogChannel: String,
  ticketCount: { type: Number, default: 0 },
  ticketBlacklist: [String],
  language: { type: String, default: 'en' },
  birthdayChannel: String,
  antinukeWhitelist: [String],
  automodWhitelist: [String],
  badWords: [String],
  capThreshold: { type: Number, default: 50 },
  spamThreshold: { type: Number, default: 5 },
  spamInterval: { type: Number, default: 5000 },
  inviteEnabled: { type: Boolean, default: true },
  capsEnabled: { type: Boolean, default: true },
  spamEnabled: { type: Boolean, default: true },
  badWordEnabled: { type: Boolean, default: true },
  automodAction: { type: String, enum: ['warn', 'mute', 'kick', 'none'], default: 'warn' },
  antinukeAction: { type: String, enum: ['ban', 'kick', 'none'], default: 'ban' },
  antinukeLogChannel: String,
  aiChannel: String,
  confessChannel: String,
});

module.exports = mongoose.model('GuildConfig', guildConfigSchema);
